<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<!--	<base href="slawa/projects/"/>-->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta http-equiv="pragma" content="no-cache"/>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="slawa/projects/index.css" />
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<title>Project Manager</title>
</head>
<body>
<h1>
	Projects in <?= basename(realpath($path)) ?>
	<a href="?path=<?=
		substr(
		str_replace(
			realpath(__DIR__.'/../../'), '',
				dirname(realpath($path)))
			, 1)
	?>">
		<i class="fa fa-level-up" aria-hidden="true"></i>
	</a>
</h1>
<div id="content">
	<?php
	echo output($p->render());
	?>
</div>
<script type="application/javascript" src="slawa/projects/projects.js"></script>
</body>
</html>
