<?php
/** @var $this FolderProject */
?>
<div class="panel panel-<?= $panelClass ?>">
	<div class="panel-heading">
		<div class="float-right">
			<?php if ($this->isPinned()) { ?>
				<a href="?path=<?= urlencode($this->path) .'&action=unpin' ?>">
					<i class="fa fa-times" aria-hidden="true"></i>
				</a>
			<?php } else { ?>
				<a href="?path=<?= urlencode($this->path) .'&action=pin' ?>">
					<i class="fa fa-thumb-tack" aria-hidden="true"></i>
				</a>
			<?php } ?>
		</div>
		<h4>
			<?= $this->showIcon() ?>
			<a href="?path=<?= urlencode($this->path) ?>" style="color: white">
				<?= basename($this->path) ?>
				(<?= $this->countFiles($this->path) ?>)
			</a>
		</h4>
	</div>
	<div class="panel-body">
		<?php if ($this->isProject()) { ?>
			<ul class="bare">
				<?= output($this->showProjectInfo()) ?>
				<?= output($this->showSubs()) ?>
			</ul>
		<?php } else { ?>
			<ul class="bare">
				<?= output($this->showSubs()) ?>
			</ul>
		<?php } ?>
	</div>
</div>
